### PR TITLE
Add support to optionally use redislite

### PR DESCRIPTION
**Pull request by dwighthubbard**

### CODE REVIEW

**Comment by prologic** [comment]
:+1: I'm defintely going to use this :)

**Comment by prologic** [comment]
@dwighthubbard I just realized; I think you made this PR against the wrong fork. See: https://github.com/kiddouk/redisco

**Comment by prologic** [comment]
Ignore my last silly comment :-) I'm merging your fork into mine and testing this out

**Comment by prologic** [comment]
So :+1: it works really nicely :)

**Comment by prologic** [comment]
Hey @dwighthubbard I tried out your patch/pull-request in my branch and I found an issue that I'd like to address:

- We need a way to be explicit about whether we use ``redis`` or ``redislite`` here.

Right now I think you use ``Redislite`` if it's "importable". The use-case I want to have for https://github.com/prologic/charla is:

```#!bash
charla --embedded
```

Makes sense? :)

**Comment by dwighthubbard** [comment]
Redislite will pass the request through to the Redis module if the user passes a hostname or socketfile of a Redis server as an argument.  This was done in order to prevent the need to write code in every app to fail back to Redis if the user doesn't want to use the embedded server.

**Pull request merged**
